source 'https://rubygems.org'

gem 'sinatra'
gem 'dm-types'
gem 'dm'
gem 'dm-timestamps'
gem 'mysql'
gem 'dm-core'
gem 'haml'
gem 'rest-client'
gem 'xml-simple'
gem 'dm-mysql-adapter'
gem 'dm-migrations'